version: '3'
services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: YNSGaming
      MYSQL_USER: root
      MYSQL_PASSWORD: Younes22
    ports:
      - "3306:3306"
    restart: unless-stopped
