name: Deploy OpenFaaS Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # nodig om commando's te kunnen uitvoeren
    - name: Download and install faas-cli
      run: curl -sLSf https://cli.openfaas.com | sudo sh 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      # bouwen van de functie zoals je dat lokaal doet
    - name: Build function only
      run: faas-cli build -f image-processing.yml
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t s129155/cloudsystemen:latest .

    - name: Push Docker image
      run: docker push s129155/cloudsystemen:latest
